app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,RadioField
from wtforms.validators import Required


class CommentForm(FlaskForm):
    description=TextAreaField('Leave a comment')
    submit=SubmitField()

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from  flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager=LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'
mail=Mail()
simple = SimpleMDE()


bootstrap = Bootstrap()
db = SQLAlchemy()

photos=UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # registering the blue print
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #setting config
    from.request import configure_request
    configure_request(app)

    from.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/auth')

    # configure UploadSet
    configure_uploads(app,photos)

    #mail
    mail.init_app(app)

    #simple mde
    simple.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from . import main
from .forms import PitchForm,CommentForm,UpvoteForm,DownvoteForm,UpdateProfile
from flask_login import login_required,current_user
from flask.views import View, MethodView
from ..model import User,Comment,Post
from ..import db,photos
from datetime import datetime
from ..request import get_quotes
import markdown2

@main.route('/')
def login():
    return redirect(url_for('auth.login'))

@main.route('/index')
def index():
    quote=get_quotes()
    print('*******quotedata*****')
    print(quote)

    allposts=Post.query.order_by(Post.date.desc()).all()
    return render_template('index.html',allposts=allposts,quote=quote)

@main.route('/about')
def about():

    return render_template('about.html')

@main.route('/post/<int:post_id>')
#displays a specific post
def post(post_id):
    post=Post.query.filter_by(id=post_id).first()
    date=post.date.strftime('%B %d, %Y')
    time=post.date.strftime('%I : %M %p')

    return render_template('post.html',post=post,date=date,time=time)

@main.route('/add' , methods=['POST','GET'])
def add():
    return render_template('add.html')

@main.route('/showpost',methods=['POST'])
def showpost():
    title=request.form['title']
    subtitle=request.form['subtitle']
    name=request.form['name']
    content=request.form['content']
    
    #creating an instance of post class
    postadded=Post(owner_id=current_user.id,title=title,subtitle=subtitle,name=name,content=content,date=datetime.now())

    #adding to the database
    db.session.add(postadded)
    db.session.commit()

    return redirect(url_for('main.index'))

@main.route('/user/<uname>')
def profile(uname):
    user=User.query.filter_by(username=uname).first()
    commentslist=Comment.get_comments(current_user.id)

    if user is None:
        abort (404)

    return render_template("profile/userprofile.html",user=user,commentslist=commentslist)

@main.route('/user/<uname>/update', methods=['GET','POST'])
@login_required

def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort (404)

    form=UpdateProfile()

    if form.validate_on_submit():
        user.bio=form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form=form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/addcomment/<int:posts_id>',methods=['POST','GET'])
def addcomment(posts_id):

    posts=Post.query.get(posts_id)

    return render_template('comment.html',posts=posts)


@main.route('/comment/<int:posts_id>', methods = ['POST'])
@login_required
def configurecomment(posts_id):
    comment=request.form['comment']
    posts=Post.query.get(posts_id)
    newcomment=Comment(id=current_user.id,comment=comment,comment_date=datetime.now())

    db.session.add(newcomment)
    db.session.commit()

    return redirect(url_for('main.displaycomment'))

@main.route('/displaycomment', methods=['POST','GET'])
def displaycomment():
    
    all_comments=Comment.query.order_by(Comment.comment_date.desc()).all()

    return render_template('displaycomment.html',all_comments = all_comments)

@main.route('/deletecomment/<int:comments_id>')

def deletecomment(comments_id):

    # newcomment=Comment(id=id,posts_id=posts_id,user_id=user_id,comment=comment,comment_date=datetime.now())

    deletecom=Comment.query.filter_by(id=comments_id).first()
    
    db.session.delete(deletecom)
    db.session.commit()

    return render_template('displaycomment.html')
    
# @main.route('/updatepost/<int:posts_id>', methods=['GET','POST'])
# @login_required
# def updatepost(posts_id):


#     blog=Post.query.filter_by(id=posts_id).first()

#     title=request.form['title']
#     subtitle=request.form['subtitle']
#     content=request.form['name']
#     name=request.form['content']
    
#     db.session.add(blog)
#     db.session.commit()

#     return redirect(url_for('.index',posts_id=blog.id))

#     return render_template('profile/updatepost.html')


@main.route('/deletepost/<int:posts_id>')
def deletepost(posts_id):
    deleteitem=Post.query.filter_by(id=posts_id).first()
    
    db.session.delete(deleteitem)
    db.session.commit()

    return redirect(url_for('main.index'))


    
    
    

app/templates/add.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Thought Pool</title>

 <!-- Bootstrap core CSS -->
 <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">

 <!-- Custom fonts for this template -->
 <link href="{{url_for('static', filename='css/all.min.css')}}" rel="stylesheet" type="text/css">
 <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
 <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

 <!-- Custom styles for this template -->
 <link href="{{url_for('static', filename='css/clean-blog.min.css')}}" rel="stylesheet">

</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{{url_for('main.index')}}">Tracy Blog</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.index')}}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.about')}}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.add')}}">Add Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.displaycomment')}}">View comments</a>
            </li>

            {%if current_user.is_authenticated%}
                <li class="nav-item">
                  <a>Current user: {{current_user.username}}</a></li>

                <li class ="nav-item">
                  <a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>

                <li class="nav-item">
                  <a href="{{url_for('auth.logout')}}">Sign out</a></li>

            {%else%}
                <li class="nav-item">
                  <a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
          </ul>
        </div>
      </div>
    </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/photos/contact-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Add Post</h1>
            <span class="subheading">Inspired? Share</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Fill out the form below to post a blog</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="addForm" id="addForm" method ='POST' action="{{url_for('main.showpost')}} " novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Title</label>
              <input type="text" class="form-control" placeholder="Title" id="title" name="title" required data-validation-required-message="Please enter a title.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Subtitle</label>
              <input type="subtitle" class="form-control" placeholder="Subtitle" id="subtitle" name ="subtitle" required data-validation-required-message="Please enter a subtitle.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Your name" id="name" name ="name"required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Content</label>
              <textarea rows="5" class="form-control" placeholder="Content" id="content" name="content" required data-validation-required-message="Please enter content."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Tracy Website 2019</p>
        </div>
      </div>
    </div>
  </footer>


  <!-- Bootstrap core JavaScript -->
<script src="{{url_for('static', filename='css/jquery.min.js')}}"></script>
<script src="{{url_for('static', filename='css/bootstrap.bundle.min.js')}}"></script>


<!-- Contact Form JavaScript -->
<script src="{{url_for('static', filename='css/jqBootstrapValidation.js')}}"></script>
<script src="{{url_for('static', filename='css/js/contact_me.js')}}"></script>


<!-- Custom scripts for this template -->
<script src="{{url_for('static', filename='css/clean-blog.min.js')}}"></script>

</body>

</html>

app/templates/fourOwfour.html
{% block content%}
<h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Thought Pool</title>

  <!-- Bootstrap core CSS -->
  <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{{url_for('static', filename='css/all.min.css')}}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{{url_for('static', filename='css/clean-blog.min.css')}}" rel="stylesheet">

</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{url_for('main.index')}}">Tracy Blog</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.index')}}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.about')}}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.add')}}">Add Post</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{{url_for('main.displaycomment')}}">View comments</a>
          </li>
          {%if current_user.is_authenticated%}
                <li class="nav-item">
                  <a>Current user: {{current_user.username}}</a></li>

                <li class ="nav-item">
                  <a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>

                <li class="nav-item">
                  <a href="{{url_for('auth.logout')}}">Sign out</a></li>

            {%else%}
                <li class="nav-item">
                  <a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
        </ul>
      </div>
    </div>
  </nav>


  <!-- Page Header -->
  <header class="masthead" style="background-image: url('../../static/photos/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1> Thought Pool</h1>
            <span class="subheading">Quote: {{quote}}</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <h3 class="post-subtitle"> Click blog to view or comment</h3>
        {%for post in allposts %}
        <div class="post-preview">
          <a href="{{url_for('main.post', post_id=post.id)}}">
            <h2 class="post-title">
            
             {{post.title}}
            </h2>
            <h3 class="post-subtitle">
              {{post.subtitle}}
            </h3>
          </a>
          <p class="post-meta">Posted by
            {{post.name}}
            on {{post.date.strftime('%B %d, %Y')}} at {{post.date.strftime('%I : %M %p')}}</p>
        </div>
        <ul class="list-inline small text-muted mt-3 mb-0">
          
          <li class="list-inline-item"><a class="btn btn-primary" href="{{url_for('main.deletepost',posts_id=post.id)}}">Delete</a></li>
          <!-- <li class="list-inline-item"><a class="btn btn-success" href="#">Edit</a></li> -->
      </ul>
        {% endfor %}     
        <hr>
        <!-- Pager -->
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Tracy Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{{url_for('static', filename='css/jquery.min.js')}}"></script>
  <script src="{{url_for('static', filename='css/bootstrap.bundle.min.js')}}"></script>

  <!-- Custom scripts for this template -->
  <script src="{{url_for('static', filename='css/clean-blog.min.js')}}"></script>

</body>

</html>

app/templates/profile/userprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Thought Pool</title>
    <!-- Bootstrap core CSS -->
 <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">

 <!-- Custom fonts for this template -->
 <link href="{{url_for('static', filename='css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
 <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
 <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

 
 <!-- Custom styles for this template -->
 <link href="{{url_for('static', filename='css/clean-blog.min.css')}}" rel="stylesheet">
 <link href="{{url_for('static', filename='css/userprofile.css')}}" rel="stylesheet">

</head>
<body>

 <!-- Navigation -->
 <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand" href="{{url_for('main.index')}}">User Profile</a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.index')}}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.about')}}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.add')}}">Add Post</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{url_for('main.displaycomment')}}">View comments</a>
              </li>
  
              {%if current_user.is_authenticated%}
              <li class="nav-item">
                    <a >Current user: {{current_user.username}}</a></li>
                <li class ="nav-item">
                <a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>

                <li class="nav-item">
                <a href="{{url_for('auth.logout')}}">Sign out</a></li>
  
              {%else%}
                <li class="nav-item">
                <a href="{{url_for('auth.login')}}">Sign in</a></li>
              {%endif%}
            </ul>
          </div>
        </div>
      </nav>
  
    <!-- Page Header -->
    <header class="masthead" style="background-image: url('../../static/photos/contact-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            
          </div>
        </div>
      </div>
    </header>  

    <!-- For demo purpose -->
<div class="row">
        <div class="col-lg-7 mx-auto text-white text-center pt-5">
            <h1 class="display-4">User profile page</h1>
            <p class="lead mb-0">{{user.username}} Profile</p>
            
        </div>
    </div><!-- End -->
    
    
    <div class="row py-5 px-4">
        <div class="col-xl-4 col-md-6 col-sm-10 mx-auto">
    
            <!-- Profile widget -->
            <div class="bg-white shadow rounded overflow-hidden">
                <div class="px-4 pt-0 pb-4 bg-dark">
                    <div class="media align-items-end profile-header">

                            {%if user.profile_pic_path%}
                            <div class="profile mr-3">
                                <img src="{{url_for('static',filename=user.profile_pic_path)}}" 
                                alt="..." width="130" class="rounded mb-2 img-thumbnail">
                                <a href="{{url_for('main.update_profile',uname=user.username)}}"
                                 class="btn btn-dark btn-sm btn-block">Edit profile</a>
                            </div>
                            {%else%}
                            <div class="py-4">
                                    <h5 class="mb-3">No profile picture</h5>
                                </div>
                            
                
                            {%if user==current_user%}
                            <div class="py-4">
                                    <h5 class="mb-3" style="color:white">Add Picture</h5>
                                    <div class="p-4 bg-light rounded shadow-sm">
                                            <form  action="{{url_for('main.update_pic',uname=user.username)}}"
                                            method="post" enctype = "multipart/form-data">
                                               <input type="file" name="photo" class="form-control" required>
                                               <input type="submit">
                                           </form>   
                                    </div>
                                </div>
                            {%endif%}
                            {%endif%}
                        
                       
                        <div class="media-body mb-5 text-white">
                            <h4 class="mt-0 mb-0">{{user.username}}</h4>
                            <p class="small mb-4"> <i class="fa fa-map-marker mr-2"></i>Kenya</p>
                        </div>
                    </div>
                </div>
    
                <div class="bg-light p-4 d-flex justify-content-end text-center">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <h5 class="font-weight-bold mb-0 d-block">241</h5><small class="text-muted"> <i class="fa fa-picture-o mr-1"></i>Photos</small>
                        </li>
                        <li class="list-inline-item">
                            <h5 class="font-weight-bold mb-0 d-block">84K</h5><small class="text-muted"> <i class="fa fa-user-circle-o mr-1"></i>Followers</small>
                        </li>
                    </ul>
                </div>
    
                <div class="py-4 px-4">
                   
                    {%if user.bio%}
                    <div class="py-4">
                        <h5 class="mb-3">User bio</h5>
                        <div class="p-4 bg-success rounded shadow-sm">
                            <p class="font-italic mb-0">{{user.bio}} </p>
                            <!-- <ul class="list-inline small text-muted mt-3 mb-0">
                                <li class="list-inline-item"><i class="fa fa-comment-o mr-2"></i>12 Comments</li>
                                <li class="list-inline-item"><i class="fa fa-heart-o mr-2"></i>200 Likes</li>
                            </ul> -->
                        </div>
                    </div>
                    {%else%}
                    <div class="py-4">
                        <h5 class="mb-3">User bio</h5>
                        <div class="p-4 bg-light rounded shadow-sm">
                            <p class="font-italic mb-0">{{user.username|capitalize}} has no bio</p>
                        </div>
                    </div>
                    {%endif%}

                    <div class="d-flex align-items-center justify-content-between mb-3">
                            <!-- <h5 class="mb-0">Recent photos</h5><a href="#" class="btn btn-link text-muted">Show all</a> -->
                        </div>
                        <div class="row">
                            <div class="col-lg-6 mb-2 pr-lg-1"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556294928/nicole-honeywill-546848-unsplash_ymprvp.jpg" alt="" class="img-fluid rounded shadow-sm"></div>
                            <div class="col-lg-6 mb-2 pl-lg-1"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556294927/dose-juice-1184444-unsplash_bmbutn.jpg" alt="" class="img-fluid rounded shadow-sm"></div>
                            <div class="col-lg-6 pr-lg-1 mb-2"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556294926/cody-davis-253925-unsplash_hsetv7.jpg" alt="" class="img-fluid rounded shadow-sm"></div>
                            <div class="col-lg-6 pl-lg-1"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556294928/tim-foster-734470-unsplash_xqde00.jpg" alt="" class="img-fluid rounded shadow-sm"></div>
                        </div>

                    <div class="py-4">
                            <h5 class="mb-3">Recent comments</h5>
                            {%for comment in commentslist%}
                            <div class="p-4 bg-info rounded shadow-sm">
                                <p class="font-italic mb-0">Date: {{comment.comment_date}}</p>
                                <p class="font-italic mb-0">Comment: {{comment.comment}}</p>
                            </div><br>
                            {%endfor%}
                            
                            
                    </div>
                </div>
            </div><!-- End profile widget -->
    
        </div>
    </div>

  <!-- Bootstrap core JavaScript -->
<script src="{{url_for('static', filename='css/jquery-3.3.1.slim.min.js')}}"></script>
<script src="{{url_for('static', filename='css/bootstrap.bundle.min.js')}}"></script>

</body>
</html>